foundation_struct:require("tests/deque_test.lua")
foundation_struct:require("tests/list_test.lua")
foundation_struct:require("tests/linked_list_test.lua")
foundation_struct:require("tests/min_heap_test.lua")
foundation_struct:require("tests/ordered_set_test.lua")
foundation_struct:require("tests/ring_buffer_test.lua")
