name = foundation_headless
description = Mocking library for some minetest structures
depends = foundation_base,foundation_stdlib,foundation_class,foundation_type_assert
optional_depends = foundation_unit_test
